id: td2021
# shareUrl: https://stateofjs.com
# questionsUrl: https://survey.devographics.com/survey/state-of-js/2022
# resultsUrl: https://2022.stateofjs.com/
year: 2021
status: 4 # preview/open/closed/hidden
# imageUrl: https://devographics.github.io/surveys/state_of_js/js2022/images/js2022.png
# faviconUrl: https://devographics.github.io/surveys/state_of_js/js2022/images/js2022-favicon.svg
# socialImageUrl: https://devographics.github.io/surveys/state_of_js/js2022/images/js2022-og.png
